2019-05-02 00:36:40,206 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:36:40.200Z","symbol":"XBTUSD","side":"Buy","size":30,"price":5285,"tickDirection":"ZeroPlusTick","trdMatchID":"d64b0df3-6048-f203-d4f2-5d4720ee5f97","grossValue":567630,"homeNotional":0.0056763,"foreignNotional":30}]}
2019-05-02 00:36:40,818 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 107, in _insert_new_bar_bitmex
    self.symbol_data['bitmex'][symbol].append(tick)
KeyError: 'XBTUSD'
2019-05-02 00:36:42,366 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:36:42.531Z","symbol":"ETHUSD","side":"Buy","size":1000,"price":158.6,"tickDirection":"ZeroPlusTick","trdMatchID":"27d7a1d2-7eea-1881-77f6-a9e997cf232f","grossValue":15860000,"homeNotional":5.293245818335803,"foreignNotional":839.5087867880584}]}
2019-05-02 00:36:42,971 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 107, in _insert_new_bar_bitmex
    self.symbol_data['bitmex'][symbol].append(tick)
KeyError: 'ETHUSD'
2019-05-02 00:36:50,033 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:36:50.177Z","symbol":"XBTUSD","side":"Sell","size":26,"price":5284.5,"tickDirection":"MinusTick","trdMatchID":"3542e796-0c6f-f6e5-ef0d-050730d3c632","grossValue":491998,"homeNotional":0.00491998,"foreignNotional":26}]}
2019-05-02 00:36:50,349 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 107, in _insert_new_bar_bitmex
    self.symbol_data['bitmex'][symbol].append(tick)
KeyError: 'XBTUSD'
2019-05-02 00:36:52,260 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:36:52.543Z","symbol":"ETHUSD","side":"Buy","size":5000,"price":158.6,"tickDirection":"ZeroPlusTick","trdMatchID":"241cedb5-f8a7-d928-3a55-a13742ac1478","grossValue":79300000,"homeNotional":26.46622909167902,"foreignNotional":4197.543933940292}]}
2019-05-02 00:38:40,632 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:38:40.761Z","symbol":"XBTUSD","side":"Buy","size":30,"price":5285,"tickDirection":"ZeroPlusTick","trdMatchID":"7528267b-c7d7-4b6e-4ce3-3bb2030b6a88","grossValue":567630,"homeNotional":0.0056763,"foreignNotional":30}]}
2019-05-02 00:38:41,237 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 107, in _insert_new_bar_bitmex
    self.symbol_data['bitmex'][symbol].append(tick)
KeyError: 'XBTUSD'
2019-05-02 00:38:42,162 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:38:42.121Z","symbol":"ETHUSD","side":"Sell","size":1500,"price":158.7,"tickDirection":"MinusTick","trdMatchID":"2c08c8ff-909f-23d8-3e3f-a4e633e33053","grossValue":23805000,"homeNotional":7.942811755361398,"foreignNotional":1260.524225575854}]}
2019-05-02 00:38:42,788 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 107, in _insert_new_bar_bitmex
    self.symbol_data['bitmex'][symbol].append(tick)
KeyError: 'ETHUSD'
2019-05-02 00:43:40,440 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:43:40.018Z","symbol":"XBTUSD","side":"Buy","size":3000,"price":5287,"tickDirection":"ZeroPlusTick","trdMatchID":"9014de0e-95d3-c20d-35e2-f5ccac683fe8","grossValue":56742000,"homeNotional":0.56742,"foreignNotional":3000}]}
2019-05-02 00:43:40,744 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'BTC/USD'
2019-05-02 00:43:53,649 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:43:53.192Z","symbol":"XBTUSD","side":"Buy","size":1000,"price":5287,"tickDirection":"ZeroPlusTick","trdMatchID":"d33c66bf-b7c9-950f-e423-15a0a7c66781","grossValue":18914000,"homeNotional":0.18914,"foreignNotional":1000}]}
2019-05-02 00:43:54,264 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'BTC/USD'
2019-05-02 00:44:02,618 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:44:02.367Z","symbol":"XBTUSD","side":"Buy","size":1,"price":5287,"tickDirection":"ZeroPlusTick","trdMatchID":"836ae494-ac3d-5dcc-016b-227640c73a07","grossValue":18914,"homeNotional":0.00018914,"foreignNotional":1}]}
2019-05-02 00:44:02,943 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'BTC/USD'
2019-05-02 00:44:04,419 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:44:04.468Z","symbol":"ETHUSD","side":"Buy","size":10000,"price":158.7,"tickDirection":"PlusTick","trdMatchID":"b79af57b-a786-f406-aee8-01605b6f55f4","grossValue":158700000,"homeNotional":52.924053982535064,"foreignNotional":8399.047367028314}]}
2019-05-02 00:44:05,019 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'ETH/USD'
2019-05-02 00:44:08,702 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-01T15:44:04.468Z","symbol":"ETHUSD","side":"Buy","size":10000,"price":158.7,"tickDirection":"PlusTick","trdMatchID":"b79af57b-a786-f406-aee8-01605b6f55f4","grossValue":158700000,"homeNotional":52.924053982535064,"foreignNotional":8399.047367028314}]}
2019-05-02 00:44:09,317 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'ETH/USD'
2019-05-02 00:44:10,108 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:44:09.174Z","symbol":"XBTUSD","side":"Buy","size":1000,"price":5287,"tickDirection":"ZeroPlusTick","trdMatchID":"0a3539ae-4f6f-bd89-4171-cc30e2485f11","grossValue":18914000,"homeNotional":0.18914,"foreignNotional":1000}]}
2019-05-02 00:44:10,401 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'BTC/USD'
2019-05-02 00:44:12,392 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-01T15:44:09.327Z","symbol":"ETHUSD","side":"Sell","size":5000,"price":158.65,"tickDirection":"MinusTick","trdMatchID":"8bd12563-ea81-d4bd-adce-e153be075e62","grossValue":79325000,"homeNotional":26.462026991267532,"foreignNotional":4198.2005821645935}]}
2019-05-02 00:44:13,004 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'ETH/USD'
2019-05-02 00:44:16,074 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-01T15:44:09.327Z","symbol":"ETHUSD","side":"Sell","size":5000,"price":158.65,"tickDirection":"MinusTick","trdMatchID":"8bd12563-ea81-d4bd-adce-e153be075e62","grossValue":79325000,"homeNotional":26.462026991267532,"foreignNotional":4198.2005821645935}]}
2019-05-02 00:44:16,381 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'ETH/USD'
2019-05-02 00:44:20,682 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:44:20.693Z","symbol":"ETHUSD","side":"Sell","size":10000,"price":158.65,"tickDirection":"ZeroMinusTick","trdMatchID":"99caf2d1-8434-769a-e5b8-d430fc73169e","grossValue":158650000,"homeNotional":52.924053982535064,"foreignNotional":8396.401164329187}]}
2019-05-02 00:44:20,974 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'ETH/USD'
2019-05-02 00:44:30,513 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:44:30.582Z","symbol":"XBTUSD","side":"Buy","size":6000,"price":5287,"tickDirection":"PlusTick","trdMatchID":"7a5ea374-ddf0-190c-02cd-0d48c7de28e4","grossValue":113484000,"homeNotional":1.13484,"foreignNotional":6000}]}
2019-05-02 00:44:30,811 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'BTC/USD'
2019-05-02 00:44:33,998 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:44:34.265Z","symbol":"ETHUSD","side":"Buy","size":10000,"price":158.7,"tickDirection":"PlusTick","trdMatchID":"89fc3df3-8597-d472-ecfc-2ae25dbb00a4","grossValue":158700000,"homeNotional":52.91845266444409,"foreignNotional":8398.158437847278}]}
2019-05-02 00:44:34,206 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-01T15:44:30.582Z","symbol":"XBTUSD","side":"Buy","size":6000,"price":5287,"tickDirection":"PlusTick","trdMatchID":"7a5ea374-ddf0-190c-02cd-0d48c7de28e4","grossValue":113484000,"homeNotional":1.13484,"foreignNotional":6000}]}
2019-05-02 00:44:34,306 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'ETH/USD'
2019-05-02 00:44:34,481 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'BTC/USD'
2019-05-02 00:44:50,172 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-01T15:44:50.123Z","symbol":"XBTUSD","side":"Buy","size":1,"price":5287,"tickDirection":"ZeroPlusTick","trdMatchID":"a5faeeb4-b08c-0138-d75b-79eed4a338ff","grossValue":18914,"homeNotional":0.00018914,"foreignNotional":1}]}
2019-05-02 00:44:50,487 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'BTC/USD'
2019-05-02 00:44:54,064 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-01T15:44:53.450Z","symbol":"XBTUSD","side":"Buy","size":1,"price":5287,"tickDirection":"ZeroPlusTick","trdMatchID":"4a0411ac-6394-9b7a-1d72-a3dad1bf04a2","grossValue":18914,"homeNotional":0.00018914,"foreignNotional":1}]}
2019-05-02 00:44:54,474 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 54, in __call__
    await self.handler(data=self.data)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/callback.py", line 21, in __call__
    await self.callback(**kwargs)
  File "/Users/davidvanisacker/Programming/Trading/backtest/datahandler/crypto/livehandler.py", line 105, in _insert_new_bar_bitmex
    tick = data[symbol]
KeyError: 'BTC/USD'
2019-05-02 01:18:02,533 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-01T16:17:51.933Z","symbol":"XBTUSD","side":"Buy","size":20000,"price":5288,"tickDirection":"ZeroPlusTick","trdMatchID":"5cc5f69f-dcf8-f14b-f422-15109ae87493","grossValue":378220000,"homeNotional":3.7822,"foreignNotional":20000}]}
2019-05-02 01:18:02,535 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-01T16:18:01.010Z","symbol":"ETHUSD","side":"Buy","size":25000,"price":158.7,"tickDirection":"PlusTick","trdMatchID":"defe0bbd-9697-c8d2-e0a8-ab5ea22f0a7b","grossValue":396750000,"homeNotional":132.4012286834022,"foreignNotional":21012.074992055925}]}
2019-05-02 01:18:02,840 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 46, in __call__
    if now < self.start_time:
TypeError: '<' not supported between instances of 'datetime.datetime' and 'float'
2019-05-02 01:18:02,843 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 46, in __call__
    if now < self.start_time:
TypeError: '<' not supported between instances of 'datetime.datetime' and 'float'
2019-05-02 01:18:05,683 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-01T16:18:01.010Z","symbol":"ETHUSD","side":"Buy","size":25000,"price":158.7,"tickDirection":"PlusTick","trdMatchID":"defe0bbd-9697-c8d2-e0a8-ab5ea22f0a7b","grossValue":396750000,"homeNotional":132.4012286834022,"foreignNotional":21012.074992055925}]}
2019-05-02 01:18:05,684 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-01T16:17:51.933Z","symbol":"XBTUSD","side":"Buy","size":20000,"price":5288,"tickDirection":"ZeroPlusTick","trdMatchID":"5cc5f69f-dcf8-f14b-f422-15109ae87493","grossValue":378220000,"homeNotional":3.7822,"foreignNotional":20000}]}
2019-05-02 01:18:05,989 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 46, in __call__
    if now < self.start_time:
TypeError: '<' not supported between instances of 'datetime.datetime' and 'float'
2019-05-02 01:18:05,990 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 46, in __call__
    if now < self.start_time:
TypeError: '<' not supported between instances of 'datetime.datetime' and 'float'
2019-05-02 01:18:09,676 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-01T16:18:01.010Z","symbol":"ETHUSD","side":"Buy","size":25000,"price":158.7,"tickDirection":"PlusTick","trdMatchID":"defe0bbd-9697-c8d2-e0a8-ab5ea22f0a7b","grossValue":396750000,"homeNotional":132.4012286834022,"foreignNotional":21012.074992055925}]}
2019-05-02 01:18:09,677 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-01T16:18:07.323Z","symbol":"XBTUSD","side":"Buy","size":3000,"price":5288,"tickDirection":"ZeroPlusTick","trdMatchID":"668bbdf4-739c-411a-397c-b8dec89247e8","grossValue":56733000,"homeNotional":0.56733,"foreignNotional":3000}]}
2019-05-02 01:18:10,291 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 46, in __call__
    if now < self.start_time:
TypeError: '<' not supported between instances of 'datetime.datetime' and 'float'
2019-05-02 01:18:10,292 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 46, in __call__
    if now < self.start_time:
TypeError: '<' not supported between instances of 'datetime.datetime' and 'float'
2019-05-20 15:57:29,721 : ERROR : Unhandled exception
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 107, in run
    loop = asyncio.get_event_loop()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
2019-05-20 16:00:32,025 : ERROR : Unhandled exception
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 107, in run
    loop = asyncio.get_event_loop()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.
2019-05-20 16:47:31,520 : WARNING : BITMEX: received no messages within timeout, restarting connection
2019-05-20 16:47:31,525 : WARNING : BITMEX: received no messages within timeout, restarting connection
2019-05-20 16:47:51,997 : WARNING : BITMEX: encountered connection issue WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason - reconnecting...
2019-05-20 16:48:01,536 : WARNING : BITMEX: encountered connection issue WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason - reconnecting...
2019-05-20 16:57:21,652 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-20T07:57:01.961Z","symbol":"XBTUSD","side":"Buy","size":2000,"price":7880.5,"tickDirection":"ZeroPlusTick","trdMatchID":"3da498ba-5d36-a43b-2c98-861faea49b6f","grossValue":25380000,"homeNotional":0.2538,"foreignNotional":2000}]}
2019-05-20 16:57:21,942 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:24,810 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-20T07:57:05.057Z","symbol":"XBTUSD","side":"Sell","size":200000,"price":7880,"tickDirection":"MinusTick","trdMatchID":"cd257315-6712-e2c8-92f4-cb90ad5e9404","grossValue":2538000000,"homeNotional":25.38,"foreignNotional":200000}]}
2019-05-20 16:57:25,272 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:25,451 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-20T07:57:06.436Z","symbol":"ETHUSD","side":"Sell","size":1200,"price":249.55,"tickDirection":"MinusTick","trdMatchID":"19826743-c2ac-fbe2-5b2c-f86ee3edc283","grossValue":29946000,"homeNotional":9.450307134981887,"foreignNotional":2358.3241455347297}]}
2019-05-20 16:57:25,767 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:28,054 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-20T07:57:09.316Z","symbol":"XBTUSD","side":"Sell","size":400,"price":7880,"tickDirection":"MinusTick","trdMatchID":"e604d297-3aad-53c9-78ff-af9813d55881","grossValue":5076000,"homeNotional":0.05076,"foreignNotional":400}]}
2019-05-20 16:57:28,282 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-20T07:57:06.436Z","symbol":"ETHUSD","side":"Sell","size":1200,"price":249.55,"tickDirection":"MinusTick","trdMatchID":"19826743-c2ac-fbe2-5b2c-f86ee3edc283","grossValue":29946000,"homeNotional":9.450307134981887,"foreignNotional":2358.3241455347297}]}
2019-05-20 16:57:28,361 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:28,567 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:31,260 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-20T07:57:12.203Z","symbol":"XBTUSD","side":"Buy","size":8935,"price":7880.5,"tickDirection":"ZeroPlusTick","trdMatchID":"7e92a705-0f55-6b62-ecd6-13911cc94f68","grossValue":113385150,"homeNotional":1.1338515,"foreignNotional":8935}]}
2019-05-20 16:57:31,544 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:32,126 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-20T07:57:12.416Z","symbol":"ETHUSD","side":"Buy","size":91,"price":249.6,"tickDirection":"PlusTick","trdMatchID":"aa2fae82-c38d-eaff-07ac-b1e01fd3f548","grossValue":2271360,"homeNotional":0.7166482910694597,"foreignNotional":178.87541345093715}]}
2019-05-20 16:57:32,413 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:34,488 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-20T07:57:14.646Z","symbol":"XBTUSD","side":"Buy","size":25,"price":7886.5,"tickDirection":"ZeroPlusTick","trdMatchID":"e21649ae-031a-4e0d-39f9-4fb7f47ee8a6","grossValue":317000,"homeNotional":0.00317,"foreignNotional":25}]}
2019-05-20 16:57:34,793 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:35,438 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-20T07:57:15.776Z","symbol":"ETHUSD","side":"Buy","size":3537,"price":249.6,"tickDirection":"ZeroPlusTick","trdMatchID":"3c041093-64d6-0a63-6958-0f92b2910590","grossValue":88283520,"homeNotional":27.854780280359112,"foreignNotional":6952.553157977634}]}
2019-05-20 16:57:35,753 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:38,481 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-20T07:57:18.703Z","symbol":"ETHUSD","side":"Buy","size":1298,"price":250,"tickDirection":"ZeroPlusTick","trdMatchID":"e45652be-4cbf-9b36-9da7-ef009a83d5f0","grossValue":32450000,"homeNotional":10.222082217672074,"foreignNotional":2555.5205544180185}]}
2019-05-20 16:57:38,788 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:39,629 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-20T07:57:18.668Z","symbol":"XBTUSD","side":"Buy","size":309,"price":7890.5,"tickDirection":"ZeroPlusTick","trdMatchID":"004dae00-0035-7a98-26a5-6c2a6e0e4f7c","grossValue":3915957,"homeNotional":0.03915957,"foreignNotional":309}]}
2019-05-20 16:57:40,004 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:42,679 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-20T07:57:23.871Z","symbol":"ETHUSD","side":"Buy","size":300,"price":250,"tickDirection":"ZeroPlusTick","trdMatchID":"05e71634-3193-fe48-c3a4-90ed5df73c99","grossValue":7500000,"homeNotional":2.362576783745472,"foreignNotional":590.644195936368}]}
2019-05-20 16:57:42,970 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:43,614 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-20T07:57:24.320Z","symbol":"XBTUSD","side":"Sell","size":100,"price":7898.5,"tickDirection":"MinusTick","trdMatchID":"a365927a-d388-ba87-da8f-6e90b4b5ae69","grossValue":1266100,"homeNotional":0.012661,"foreignNotional":100}]}
2019-05-20 16:57:43,930 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:45,854 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-20T07:57:25.840Z","symbol":"ETHUSD","side":"Buy","size":100,"price":250,"tickDirection":"ZeroPlusTick","trdMatchID":"ac6db878-5a58-404f-3f56-59c5f445352e","grossValue":2500000,"homeNotional":0.7875255945818239,"foreignNotional":196.881398645456}]}
2019-05-20 16:57:46,162 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:47,566 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-20T07:57:27.439Z","symbol":"XBTUSD","side":"Buy","size":327,"price":7904.5,"tickDirection":"ZeroPlusTick","trdMatchID":"9facae9e-2476-1409-a9f2-b752422b2ee2","grossValue":4136877,"homeNotional":0.04136877,"foreignNotional":327}]}
2019-05-20 16:57:47,829 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:49,003 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-20T07:57:29.102Z","symbol":"ETHUSD","side":"Buy","size":700,"price":250.15,"tickDirection":"ZeroPlusTick","trdMatchID":"c88dc5a1-db17-9753-617d-3094ddbad7f6","grossValue":17510500,"homeNotional":5.512679162072767,"foreignNotional":1378.9966923925028}]}
2019-05-20 16:57:49,289 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:50,608 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-20T07:57:30.707Z","symbol":"XBTUSD","side":"Buy","size":276,"price":7904.5,"tickDirection":"ZeroPlusTick","trdMatchID":"1993248a-c309-7eed-5787-9a96de1722eb","grossValue":3491676,"homeNotional":0.03491676,"foreignNotional":276}]}
2019-05-20 16:57:50,898 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:52,972 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-20T07:57:31.506Z","symbol":"ETHUSD","side":"Sell","size":500,"price":250.1,"tickDirection":"ZeroMinusTick","trdMatchID":"d8a8876f-88e0-8238-df88-3c8c5bfd7c64","grossValue":12505000,"homeNotional":3.9503831871691553,"foreignNotional":987.9908351110058}]}
2019-05-20 16:57:53,263 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:53,841 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-20T07:57:34.697Z","symbol":"XBTUSD","side":"Sell","size":22922,"price":7902,"tickDirection":"MinusTick","trdMatchID":"7fed4301-59fc-0856-0a73-fec96ff4b5e9","grossValue":290077910,"homeNotional":2.9007791,"foreignNotional":22922}]}
2019-05-20 16:57:54,148 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:57,527 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"ETHUSD"},"data":[{"timestamp":"2019-05-20T07:57:36.407Z","symbol":"ETHUSD","side":"Sell","size":98,"price":250.1,"tickDirection":"MinusTick","trdMatchID":"d2030154-4fbf-0d1e-bc63-b8d24bc76bfe","grossValue":2450980,"homeNotional":0.7742751046851545,"foreignNotional":193.64620368175713}]}
2019-05-20 16:57:58,119 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:57:59,063 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-20T07:57:37.357Z","symbol":"XBTUSD","side":"Buy","size":1388,"price":7902.5,"tickDirection":"ZeroPlusTick","trdMatchID":"713e10c5-346a-584e-6679-42110bf14460","grossValue":17563752,"homeNotional":0.17563752,"foreignNotional":1388}]}
2019-05-20 16:57:59,326 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 63, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'decimal.Decimal'
2019-05-20 16:58:02,748 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-20T07:57:43.386Z","symbol":"XBTUSD","side":"Sell","size":1,"price":7888.5,"tickDirection":"MinusTick","trdMatchID":"ec1044be-6d01-014e-b644-bdf9443d85ea","grossValue":12677,"homeNotional":0.00012677,"foreignNotional":1}]}
2019-05-20 17:03:00,112 : ERROR : BITMEX: error handling message {"table":"trade","action":"insert","data":[{"timestamp":"2019-05-20T08:02:41.309Z","symbol":"XBTUSD","side":"Buy","size":25,"price":7895,"tickDirection":"PlusTick","trdMatchID":"a6765e07-e582-f036-26a6-988cd3735549","grossValue":316650,"homeNotional":0.0031665,"foreignNotional":25},{"timestamp":"2019-05-20T08:02:41.309Z","symbol":"XBTUSD","side":"Buy","size":4975,"price":7895,"tickDirection":"ZeroPlusTick","trdMatchID":"92112c33-7089-6ae6-d397-573eaf49a903","grossValue":63013350,"homeNotional":0.6301335,"foreignNotional":4975}]}
2019-05-20 17:03:00,419 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 60, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'decimal.Decimal' and 'float'
2019-05-20 17:03:03,473 : ERROR : BITMEX: error handling message {"table":"trade","action":"partial","keys":[],"types":{"timestamp":"timestamp","symbol":"symbol","side":"symbol","size":"long","price":"float","tickDirection":"symbol","trdMatchID":"guid","grossValue":"long","homeNotional":"float","foreignNotional":"float"},"foreignKeys":{"symbol":"instrument","side":"side"},"attributes":{"timestamp":"sorted","symbol":"grouped"},"filter":{"symbol":"XBTUSD"},"data":[{"timestamp":"2019-05-20T08:02:44.314Z","symbol":"XBTUSD","side":"Buy","size":1000,"price":7894.5,"tickDirection":"PlusTick","trdMatchID":"22dd6f6e-df72-6b3a-6c1c-2f644d893ba8","grossValue":12667000,"homeNotional":0.12667,"foreignNotional":1000}]}
2019-05-20 17:03:03,755 : ERROR : BITMEX: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 163, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 181, in _handler
    await handler(message)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 220, in message_handler
    await self._trade(msg)
  File "/Users/davidvanisacker/backtest/lib/python3.7/site-packages/cryptofeed/bitmex/bitmex.py", line 84, in _trade
    timestamp=data['timestamp'])
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 60, in __call__
    self._agg(pair, amount, price)
  File "/Users/davidvanisacker/Programming/Trading/backtest/utils/aggregate.py", line 34, in _agg
    self.data[pair]['volume'] += amount
TypeError: unsupported operand type(s) for +=: 'decimal.Decimal' and 'float'
